# --- Database Persistent Volume Claim ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce # Allow only one node to mount at a time
  resources:
    requests:
      storage: 5Gi # Request 5 Gigabytes of storage